name = "template"
type = "javascript"
workers_dev = true
account_id = "7e1ed268338bee137ae5a757863ccb9c"
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format="service-worker"
